### ISSUE TITLE
[plugins/renovate-backend] extract Redis cache config and use it to configure Renovate

### ISSUE THREAD

**Issue by secustor** [secustor/backstage-plugins#46]
```yaml
backend:
  cache:
    store: redis
    connection: redis://user:pass@cache.example.com:6379
```

https://docs.renovatebot.com/self-hosted-configuration/#redisurl
